### ISSUE TITLE
Add support for 50 and 100 Minegeld notes

### ISSUE THREAD

**Issue by Wuzzy2** [mt-mods/atm#12]
Currently, ATMs only support 1, 5 and 10 Minegeld notes but the currency mod also has 50 and 100 Minegeld notes.

**Comment by OgelGames** [comment]
Funny, I was just thinking about this the other day. ATMs require too much clicking.

**Comment by Wuzzy2** [comment]
A PR from my side is in the works.

**Comment by Niklp09** [comment]
Already done @Wuzzy2 https://github.com/mt-mods/atm/pull/13
